name: GitHub Actions Demo
on: 
  push:
    branches: [main]
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World ${{ github.event_name }}"

      - uses: actions/checkout@v4

      - run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree 

 
